### ISSUE TITLE
Does "responsive resize" work?

### ISSUE THREAD

**Issue by iHedgehog** [w8tcha/CKEditor-oEmbed-Plugin#77]
As far as I understand "responsiveness" content must become smaller when I shrink browser window, but iframe stays the same size and goes out of the parent div.embeddedContent block.

![1](https://cloud.githubusercontent.com/assets/6762673/8055284/098e3f28-0ea7-11e5-8a0b-d8243f59f9b3.png)

I have tried this with youtube, vimeo, dailymotion videos and plugin acts the same.

**Comment by w8tcha** [comment]
> As far as I understand "responsiveness" content must become smaller when I shrink browser window, 

No thats not was that function does, sorry if it is not really clear, Responsive resize is does only mean that the video is shrinked to the max height and weight while keeping the correct aspect ratio.

**Comment by iHedgehog** [comment]
> No thats not was that function does, sorry if it is not really clear, Responsive resize is does only mean that the video is shrinked to the max height and weight while keeping the correct aspect ratio.

Oh, I see. It is confusing a little. I think it should be called "Keep aspect ration" or something like this and be just a checkbox with "Specific Resize" option.
So, maybe, will you think about adding "responsive resize" in classic meaning? 😀 It would be very useful.

**Comment by w8tcha** [comment]
> So, maybe, will you think about adding "responsive resize" in classic meaning? 😀 It would be very useful

You can do that via css its much easier..

```css
.embeddedContent { 
position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; 
}

.embeddedContent iframe, 
.embeddedContent object, 
.embeddedContent embed { 
position: absolute; top: 0; left: 0; width: 100%; height: 100%; 
}
```
